// <auto-generated />
using System;
using ConsultantManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultantManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("ConsultantManagementApi.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsultantRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantRoleId");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.ConsultantRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsultantRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 45, 15, 365, DateTimeKind.Utc).AddTicks(7240),
                            Name = "Consultant Level 1",
                            RatePerHour = 50.00m,
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 45, 15, 365, DateTimeKind.Utc).AddTicks(7240)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 45, 15, 365, DateTimeKind.Utc).AddTicks(7240),
                            Name = "Consultant Level 2",
                            RatePerHour = 75.00m,
                            UpdatedAt = new DateTime(2025, 12, 17, 10, 45, 15, 365, DateTimeKind.Utc).AddTicks(7240)
                        });
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.ConsultantTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.TaskAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 10, 45, 15, 463, DateTimeKind.Utc).AddTicks(6710),
                            PasswordHash = "$2a$11$qkw2SXZtp9RKTBM2B8OcTehFL7UG7c/vPHAVY34owhNXttX0v108y",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.WorkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerHourAtTimeOfWork")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkEntries");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.Consultant", b =>
                {
                    b.HasOne("ConsultantManagementApi.Models.ConsultantRole", "ConsultantRole")
                        .WithMany("Consultants")
                        .HasForeignKey("ConsultantRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultantRole");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.TaskAssignment", b =>
                {
                    b.HasOne("ConsultantManagementApi.Models.Consultant", "Consultant")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultantManagementApi.Models.ConsultantTask", "Task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.WorkEntry", b =>
                {
                    b.HasOne("ConsultantManagementApi.Models.Consultant", "Consultant")
                        .WithMany("WorkEntries")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultantManagementApi.Models.ConsultantTask", "Task")
                        .WithMany("WorkEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.Consultant", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.ConsultantRole", b =>
                {
                    b.Navigation("Consultants");
                });

            modelBuilder.Entity("ConsultantManagementApi.Models.ConsultantTask", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("WorkEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
